# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(32, 74, 135, 255), stop:0.597015 rgba(48, 140, 198, 255));\n"
"border-radius:20px;")
        self.main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.main_layout = QtWidgets.QVBoxLayout(self.main)
        self.main_layout.setContentsMargins(9, -1, -1, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.title_bar = QtWidgets.QFrame(self.main)
        self.title_bar.setMinimumSize(QtCore.QSize(0, 0))
        self.title_bar.setMaximumSize(QtCore.QSize(16777215, 50))
        self.title_bar.setStyleSheet("background-color:none;")
        self.title_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.titlebar_layout = QtWidgets.QHBoxLayout(self.title_bar)
        self.titlebar_layout.setContentsMargins(-1, 2, -1, -1)
        self.titlebar_layout.setSpacing(2)
        self.titlebar_layout.setObjectName("titlebar_layout")
        self.frame_title = QtWidgets.QFrame(self.title_bar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.frame_title.setFont(font)
        self.frame_title.setStyleSheet("background-color:none;")
        self.frame_title.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title.setObjectName("frame_title")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_title)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lbl_title = QtWidgets.QLabel(self.frame_title)
        font = QtGui.QFont()
        font.setFamily("FreeSans")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_title.setFont(font)
        self.lbl_title.setStyleSheet("color: rgb(169, 232, 242);")
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout_2.addWidget(self.lbl_title)
        self.titlebar_layout.addWidget(self.frame_title)
        self.frame_btn = QtWidgets.QFrame(self.title_bar)
        self.frame_btn.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.frame_btn.setFont(font)
        self.frame_btn.setStyleSheet("background-color:none;")
        self.frame_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btn.setObjectName("frame_btn")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_btn)
        self.horizontalLayout_2.setContentsMargins(10, 2, 2, -1)
        self.horizontalLayout_2.setSpacing(9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_max = QtWidgets.QPushButton(self.frame_btn)
        self.btn_max.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_max.setMaximumSize(QtCore.QSize(18, 18))
        self.btn_max.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(37,211,102);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(37,211,102, 150);\n"
"}")
        self.btn_max.setText("")
        self.btn_max.setObjectName("btn_max")
        self.horizontalLayout_2.addWidget(self.btn_max)
        self.btn_min = QtWidgets.QPushButton(self.frame_btn)
        self.btn_min.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_min.setMaximumSize(QtCore.QSize(18, 18))
        self.btn_min.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(255,170,0);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(255,170,0, 150);\n"
"}")
        self.btn_min.setText("")
        self.btn_min.setObjectName("btn_min")
        self.horizontalLayout_2.addWidget(self.btn_min)
        self.btn_exit = QtWidgets.QPushButton(self.frame_btn)
        self.btn_exit.setMinimumSize(QtCore.QSize(16, 16))
        self.btn_exit.setMaximumSize(QtCore.QSize(18, 18))
        self.btn_exit.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius:8px;\n"
"    background-color:rgb(239,89,70);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(239,89,70, 150);\n"
"}")
        self.btn_exit.setText("")
        self.btn_exit.setObjectName("btn_exit")
        self.horizontalLayout_2.addWidget(self.btn_exit)
        self.titlebar_layout.addWidget(self.frame_btn, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.main_layout.addWidget(self.title_bar)
        self.content = QtWidgets.QFrame(self.main)
        self.content.setStyleSheet("background-color:none;")
        self.content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content.setObjectName("content")
        self.content_layout = QtWidgets.QVBoxLayout(self.content)
        self.content_layout.setObjectName("content_layout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_home = QtWidgets.QWidget()
        self.page_home.setObjectName("page_home")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_home)
        self.verticalLayout_5.setContentsMargins(128, 0, 128, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.fr_stream_video = QtWidgets.QFrame(self.page_home)
        self.fr_stream_video.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.fr_stream_video.setStyleSheet("border-radius:8px;\n"
"background-color: rgb(0,0,0);\n"
"border-width: 0px;\n"
"")
        self.fr_stream_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_stream_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_stream_video.setObjectName("fr_stream_video")
        self.stream_layout = QtWidgets.QVBoxLayout(self.fr_stream_video)
        self.stream_layout.setContentsMargins(0, 0, 0, 0)
        self.stream_layout.setSpacing(0)
        self.stream_layout.setObjectName("stream_layout")
        self.label_img_stream = QtWidgets.QLabel(self.fr_stream_video)
        self.label_img_stream.setStyleSheet("color: rgb(238, 238, 236);")
        self.label_img_stream.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_stream.setObjectName("label_img_stream")
        self.stream_layout.addWidget(self.label_img_stream)
        self.lbl_name = QtWidgets.QLabel(self.fr_stream_video)
        self.lbl_name.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_name.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        self.lbl_name.setFont(font)
        self.lbl_name.setStyleSheet("color: rgb(0,0,0);\n"
"border-radius: 10;\n"
"background-color: rgb(238, 238, 236);")
        self.lbl_name.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name.setObjectName("lbl_name")
        self.stream_layout.addWidget(self.lbl_name)
        self.verticalLayout_5.addWidget(self.fr_stream_video)
        self.fr_ctn_btn = QtWidgets.QFrame(self.page_home)
        self.fr_ctn_btn.setMinimumSize(QtCore.QSize(0, 0))
        self.fr_ctn_btn.setMaximumSize(QtCore.QSize(16777215, 50))
        self.fr_ctn_btn.setStyleSheet("border-radius:8px;")
        self.fr_ctn_btn.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_ctn_btn.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_ctn_btn.setObjectName("fr_ctn_btn")
        self.icon_btn_layout = QtWidgets.QHBoxLayout(self.fr_ctn_btn)
        self.icon_btn_layout.setContentsMargins(0, 0, 0, 0)
        self.icon_btn_layout.setSpacing(72)
        self.icon_btn_layout.setObjectName("icon_btn_layout")
        self.btn_text = QtWidgets.QPushButton(self.fr_ctn_btn)
        self.btn_text.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_text.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_text.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_text.setStyleSheet("border-image: url(:/img2/mail2.png);")
        self.btn_text.setText("")
        self.btn_text.setIconSize(QtCore.QSize(35, 35))
        self.btn_text.setObjectName("btn_text")
        self.icon_btn_layout.addWidget(self.btn_text)
        self.btn_call = QtWidgets.QPushButton(self.fr_ctn_btn)
        self.btn_call.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_call.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_call.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_call.setStyleSheet("border-image: url(:/img2/call.png);")
        self.btn_call.setText("")
        self.btn_call.setObjectName("btn_call")
        self.icon_btn_layout.addWidget(self.btn_call)
        self.btn_mail = QtWidgets.QPushButton(self.fr_ctn_btn)
        self.btn_mail.setMinimumSize(QtCore.QSize(40, 50))
        self.btn_mail.setMaximumSize(QtCore.QSize(40, 50))
        self.btn_mail.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_mail.setStyleSheet("border-image: url(:/img2/mail.png);")
        self.btn_mail.setText("")
        self.btn_mail.setObjectName("btn_mail")
        self.icon_btn_layout.addWidget(self.btn_mail)
        self.verticalLayout_5.addWidget(self.fr_ctn_btn, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.page_home)
        self.page_credits = QtWidgets.QWidget()
        self.page_credits.setObjectName("page_credits")
        self.tableView = QtWidgets.QTableView(self.page_credits)
        self.tableView.setGeometry(QtCore.QRect(370, 140, 256, 192))
        self.tableView.setObjectName("tableView")
        self.stackedWidget.addWidget(self.page_credits)
        self.content_layout.addWidget(self.stackedWidget)
        self.main_layout.addWidget(self.content)
        self.credits = QtWidgets.QFrame(self.main)
        self.credits.setMaximumSize(QtCore.QSize(16777215, 30))
        self.credits.setStyleSheet("background-color:none;")
        self.credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.credits.setObjectName("credits")
        self.credits_layout = QtWidgets.QHBoxLayout(self.credits)
        self.credits_layout.setContentsMargins(0, 0, 0, 0)
        self.credits_layout.setSpacing(0)
        self.credits_layout.setObjectName("credits_layout")
        self.frame_title_credits = QtWidgets.QFrame(self.credits)
        self.frame_title_credits.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title_credits.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_credits.setObjectName("frame_title_credits")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_title_credits)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_title_credits = QtWidgets.QLabel(self.frame_title_credits)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(8)
        font.setStrikeOut(False)
        self.label_title_credits.setFont(font)
        self.label_title_credits.setStyleSheet("color: rgb(169, 232, 242);")
        self.label_title_credits.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_title_credits.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_title_credits.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_credits.setObjectName("label_title_credits")
        self.verticalLayout.addWidget(self.label_title_credits)
        self.credits_layout.addWidget(self.frame_title_credits)
        self.frame_grip = QtWidgets.QFrame(self.credits)
        self.frame_grip.setMinimumSize(QtCore.QSize(25, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(25, 25))
        self.frame_grip.setStyleSheet("padding:5px; border-radius:5px;")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.credits_layout.addWidget(self.frame_grip)
        self.main_layout.addWidget(self.credits)
        self.verticalLayout_4.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lbl_title.setText(_translate("MainWindow", "Door Lock | "))
        self.btn_max.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_min.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_exit.setToolTip(_translate("MainWindow", "Close"))
        self.label_img_stream.setText(_translate("MainWindow", "loading ...."))
        self.lbl_name.setText(_translate("MainWindow", "..."))
        self.label_title_credits.setText(_translate("MainWindow", "PT. AITI DIGITAL INDONESIA"))

import test_2_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

