# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!
print("ui_main2.py")
from config import get_configs

conf = get_configs()

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 600))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: none;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.Layout_central_widget = QtWidgets.QVBoxLayout(self.centralwidget)
        self.Layout_central_widget.setContentsMargins(0, 0, 0, 0)
        self.Layout_central_widget.setSpacing(0)
        self.Layout_central_widget.setObjectName("Layout_central_widget")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.871, y2:1, stop:0.288557 rgba(48, 147, 198, 255), stop:0.970149 rgba(86, 202, 205, 255));\n"
"border-radius:10px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.Layout_main = QtWidgets.QHBoxLayout(self.main)
        self.Layout_main.setContentsMargins(8, 8, 8, 8)
        self.Layout_main.setSpacing(0)
        self.Layout_main.setObjectName("Layout_main")
        self.frame_info = QtWidgets.QFrame(self.main)
        self.frame_info.setStyleSheet("background-color: none;")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.Layout_frame_info = QtWidgets.QVBoxLayout(self.frame_info)
        self.Layout_frame_info.setObjectName("Layout_frame_info")
        self.fr_jam = QtWidgets.QFrame(self.frame_info)
        self.fr_jam.setMaximumSize(QtCore.QSize(16777215, 130))
        self.fr_jam.setStyleSheet("background-color:none;")
        self.fr_jam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_jam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_jam.setObjectName("fr_jam")
        self.Layout_fr_jam = QtWidgets.QVBoxLayout(self.fr_jam)
        self.Layout_fr_jam.setContentsMargins(-1, 0, -1, 0)
        self.Layout_fr_jam.setObjectName("Layout_fr_jam")
        self.lbl_jam = QtWidgets.QLabel(self.fr_jam)
        self.lbl_jam.setStyleSheet("font: 25 75pt light \"Ubuntu\";\n"
"font-size:55pt;\n"
"color: rgb(238, 238, 236);")
        self.lbl_jam.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_jam.setObjectName("lbl_jam")
        self.Layout_fr_jam.addWidget(self.lbl_jam)
        self.Layout_frame_info.addWidget(self.fr_jam)
        self.fr_tanggal = QtWidgets.QFrame(self.frame_info)
        self.fr_tanggal.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_tanggal.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fr_tanggal.setStyleSheet("background-color: none;")
        self.fr_tanggal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_tanggal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_tanggal.setObjectName("fr_tanggal")
        self.Layout_fr_tanggal = QtWidgets.QVBoxLayout(self.fr_tanggal)
        self.Layout_fr_tanggal.setContentsMargins(-1, 0, -1, -1)
        self.Layout_fr_tanggal.setObjectName("Layout_fr_tanggal")
        self.lbl_tanggal = QtWidgets.QLabel(self.fr_tanggal)
        self.lbl_tanggal.setStyleSheet("font: 57 35pt \"Roboto\";\n"
"font-size:25pt;\n"
"color: rgb(238, 238, 236);")
        self.lbl_tanggal.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_tanggal.setObjectName("lbl_tanggal")
        self.Layout_fr_tanggal.addWidget(self.lbl_tanggal)
        self.Layout_frame_info.addWidget(self.fr_tanggal)
        self.fr_call = QtWidgets.QFrame(self.frame_info)
        self.fr_call.setStyleSheet("background-color:none;")
        self.fr_call.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_call.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_call.setObjectName("fr_call")
        self.Layout_fr_call = QtWidgets.QVBoxLayout(self.fr_call)
        self.Layout_fr_call.setObjectName("Layout_fr_call")
        self.btn_call = QtWidgets.QPushButton(self.fr_call)
        self.btn_call.setMinimumSize(QtCore.QSize(110, 110))
        self.btn_call.setMaximumSize(QtCore.QSize(120, 120))
        self.btn_call.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_call.setStyleSheet("border-image: url(:/icons/icon_set/call_btnic_call.png);")
        self.btn_call.setText("")
        self.btn_call.setIconSize(QtCore.QSize(16, 16))
        self.btn_call.setFlat(False)
        self.btn_call.setObjectName("btn_call")
        self.Layout_fr_call.addWidget(self.btn_call, 0, QtCore.Qt.AlignHCenter)
        self.lbl_info_call = QtWidgets.QLabel(self.fr_call)
        self.lbl_info_call.setStyleSheet("color: rgb(252, 175, 62);\n"
"font: 57 italic 11pt \"Roboto\";\n"
"")
        self.lbl_info_call.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_info_call.setObjectName("lbl_info_call")
        self.Layout_fr_call.addWidget(self.lbl_info_call)
        self.Layout_frame_info.addWidget(self.fr_call)
        self.fr_pintu = QtWidgets.QFrame(self.frame_info)
        self.fr_pintu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_pintu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_pintu.setObjectName("fr_pintu")
        self.Layout_fr_pintu = QtWidgets.QHBoxLayout(self.fr_pintu)
        self.Layout_fr_pintu.setObjectName("Layout_fr_pintu")
        self.label = QtWidgets.QLabel(self.fr_pintu)
        self.label.setMinimumSize(QtCore.QSize(0, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 75 30pt bold \"Roboto\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.Layout_fr_pintu.addWidget(self.label)
        self.Layout_frame_info.addWidget(self.fr_pintu)
        self.Layout_main.addWidget(self.frame_info)
        self.frame_recog = QtWidgets.QFrame(self.main)
        self.frame_recog.setMinimumSize(QtCore.QSize(608, 0))
        self.frame_recog.setStyleSheet("background-color: none;")
        self.frame_recog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_recog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_recog.setObjectName("frame_recog")
        self.Layout_frame_recog = QtWidgets.QVBoxLayout(self.frame_recog)
        self.Layout_frame_recog.setContentsMargins(9, 9, 0, 9)
        self.Layout_frame_recog.setObjectName("Layout_frame_recog")
        self.fr_video = QtWidgets.QFrame(self.frame_recog)
        self.fr_video.setMinimumSize(QtCore.QSize(0, 450))
        self.fr_video.setStyleSheet("border-radius:20px;")
        self.fr_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_video.setObjectName("fr_video")
        self.Layout_fr_video = QtWidgets.QVBoxLayout(self.fr_video)
        self.Layout_fr_video.setObjectName("Layout_fr_video")
        self.lbl_video = QtWidgets.QLabel(self.fr_video)
        self.lbl_video.setMaximumSize(QtCore.QSize(608, 16777215))
        self.lbl_video.setStyleSheet("border-radius:20px;")
        self.lbl_video.setFrameShadow(QtWidgets.QFrame.Plain)
        self.lbl_video.setScaledContents(True)
        self.lbl_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video.setObjectName("lbl_video")
        self.Layout_fr_video.addWidget(self.lbl_video)
        self.Layout_frame_recog.addWidget(self.fr_video)
        self.fr_name_plate = QtWidgets.QFrame(self.frame_recog)
        self.fr_name_plate.setMinimumSize(QtCore.QSize(300, 100))
        self.fr_name_plate.setMaximumSize(QtCore.QSize(99999, 100))
        self.fr_name_plate.setStyleSheet("")
        self.fr_name_plate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_name_plate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_name_plate.setObjectName("fr_name_plate")
        self.Layout_fr_name_plate = QtWidgets.QHBoxLayout(self.fr_name_plate)
        self.Layout_fr_name_plate.setContentsMargins(54, -1, 54, -1)
        self.Layout_fr_name_plate.setObjectName("Layout_fr_name_plate")
        self.fr_wadah_recog = QtWidgets.QFrame(self.fr_name_plate)
        self.fr_wadah_recog.setStyleSheet("border-image: url(:/icons/icon_set/wadah nama.png);")
        self.fr_wadah_recog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_wadah_recog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_wadah_recog.setLineWidth(7)
        self.fr_wadah_recog.setMidLineWidth(1)
        self.fr_wadah_recog.setObjectName("fr_wadah_recog")
        self.Layout_wadah_prediksi = QtWidgets.QHBoxLayout(self.fr_wadah_recog)
        self.Layout_wadah_prediksi.setContentsMargins(18, -1, 9, -1)
        self.Layout_wadah_prediksi.setObjectName("Layout_wadah_prediksi")
        self.lbl_icon_lock = QtWidgets.QLabel(self.fr_wadah_recog)
        self.lbl_icon_lock.setMaximumSize(QtCore.QSize(60, 60))
        self.lbl_icon_lock.setStyleSheet("border-image: url(:/icons/icon_set/lock.png);")
        self.lbl_icon_lock.setText("")
        self.lbl_icon_lock.setObjectName("lbl_icon_lock")
        self.Layout_wadah_prediksi.addWidget(self.lbl_icon_lock)
        self.lbl_name_recog = QtWidgets.QLabel(self.fr_wadah_recog)
        self.lbl_name_recog.setStyleSheet("border-image: none; font-size:20pt;")
        self.lbl_name_recog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.lbl_name_recog.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_name_recog.setObjectName("lbl_name_recog")
        self.Layout_wadah_prediksi.addWidget(self.lbl_name_recog)
        self.lbl_count = QtWidgets.QLabel(self.fr_wadah_recog)
        self.lbl_count.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lbl_count.setStyleSheet("border-image:none;")
        self.lbl_count.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_count.setText("")
        self.lbl_count.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_count.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_count.setObjectName("lbl_count")
        self.Layout_wadah_prediksi.addWidget(self.lbl_count)
        self.Layout_fr_name_plate.addWidget(self.fr_wadah_recog)
        self.Layout_frame_recog.addWidget(self.fr_name_plate)
        self.Layout_main.addWidget(self.frame_recog)
        self.Layout_central_widget.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AITI Check In"))
        self.lbl_jam.setText(_translate("MainWindow", "19:30"))
        self.lbl_tanggal.setText(_translate("MainWindow", "Fri, 29 Aug"))
        self.lbl_info_call.setText(_translate("MainWindow", "Press Call If You Not Yet Registed"))
        self.label.setText(_translate("MainWindow", conf.doorlock.name))
        self.lbl_video.setText(_translate("MainWindow", "loading..."))
        self.lbl_name_recog.setText(_translate("MainWindow", "Tidak Dikenali"))

import ui_icon_set_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

