# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 600)
        MainWindow.setMinimumSize(QtCore.QSize(300, 200))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(85, 87, 83);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Layout_central_widget = QtWidgets.QVBoxLayout(self.centralwidget)
        self.Layout_central_widget.setContentsMargins(0, 0, 0, 0)
        self.Layout_central_widget.setSpacing(0)
        self.Layout_central_widget.setObjectName("Layout_central_widget")
        self.main = QtWidgets.QFrame(self.centralwidget)
        self.main.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.main.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0.871, y2:1, stop:0.288557 rgba(48, 147, 198, 255), stop:0.970149 rgba(86, 202, 205, 255));\n"
"border-radius:10px;")
        self.main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main.setObjectName("main")
        self.Layout_main = QtWidgets.QHBoxLayout(self.main)
        self.Layout_main.setContentsMargins(8, 8, 8, 8)
        self.Layout_main.setSpacing(0)
        self.Layout_main.setObjectName("Layout_main")
        self.frame_info = QtWidgets.QFrame(self.main)
        self.frame_info.setStyleSheet("background-color: none;")
        self.frame_info.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_info.setObjectName("frame_info")
        self.Layout_frame_info = QtWidgets.QVBoxLayout(self.frame_info)
        self.Layout_frame_info.setObjectName("Layout_frame_info")
        self.fr_jam = QtWidgets.QFrame(self.frame_info)
        self.fr_jam.setStyleSheet("background-color:none;")
        self.fr_jam.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_jam.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_jam.setObjectName("fr_jam")
        self.Layout_fr_jam = QtWidgets.QVBoxLayout(self.fr_jam)
        self.Layout_fr_jam.setContentsMargins(-1, -1, -1, 0)
        self.Layout_fr_jam.setObjectName("Layout_fr_jam")
        self.lbl_jam = QtWidgets.QLabel(self.fr_jam)
        self.lbl_jam.setStyleSheet("font: 25 80pt light \"Ubuntu\";\n"
"color: rgb(238, 238, 236);")
        self.lbl_jam.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.lbl_jam.setObjectName("lbl_jam")
        self.Layout_fr_jam.addWidget(self.lbl_jam)
        self.Layout_frame_info.addWidget(self.fr_jam)
        self.fr_tanggal = QtWidgets.QFrame(self.frame_info)
        self.fr_tanggal.setMinimumSize(QtCore.QSize(0, 50))
        self.fr_tanggal.setMaximumSize(QtCore.QSize(16777215, 80))
        self.fr_tanggal.setStyleSheet("background-color: none;")
        self.fr_tanggal.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_tanggal.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_tanggal.setObjectName("fr_tanggal")
        self.Layout_fr_tanggal = QtWidgets.QVBoxLayout(self.fr_tanggal)
        self.Layout_fr_tanggal.setContentsMargins(-1, 0, -1, -1)
        self.Layout_fr_tanggal.setObjectName("Layout_fr_tanggal")
        self.lbl_tanggal = QtWidgets.QLabel(self.fr_tanggal)
        self.lbl_tanggal.setStyleSheet("font: 57 40pt \"Roboto\";\n"
"color: rgb(238, 238, 236);")
        self.lbl_tanggal.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lbl_tanggal.setObjectName("lbl_tanggal")
        self.Layout_fr_tanggal.addWidget(self.lbl_tanggal)
        self.Layout_frame_info.addWidget(self.fr_tanggal)
        self.fr_call = QtWidgets.QFrame(self.frame_info)
        self.fr_call.setStyleSheet("background-color:none;")
        self.fr_call.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_call.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_call.setObjectName("fr_call")
        self.Layout_fr_call = QtWidgets.QVBoxLayout(self.fr_call)
        self.Layout_fr_call.setObjectName("Layout_fr_call")
        self.ic_call = QtWidgets.QLabel(self.fr_call)
        self.ic_call.setMinimumSize(QtCore.QSize(0, 120))
        self.ic_call.setText("")
        self.ic_call.setPixmap(QtGui.QPixmap(":/icons/icon_set/call_btnic_call.png"))
        self.ic_call.setAlignment(QtCore.Qt.AlignCenter)
        self.ic_call.setObjectName("ic_call")
        self.Layout_fr_call.addWidget(self.ic_call)
        self.label_2 = QtWidgets.QLabel(self.fr_call)
        self.label_2.setStyleSheet("color: rgb(252, 175, 62);\n"
"font: 57 italic 8pt \"Roboto\";\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.Layout_fr_call.addWidget(self.label_2)
        self.Layout_frame_info.addWidget(self.fr_call)
        self.fr_pintu = QtWidgets.QFrame(self.frame_info)
        self.fr_pintu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_pintu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_pintu.setObjectName("fr_pintu")
        self.Layout_fr_pintu = QtWidgets.QHBoxLayout(self.fr_pintu)
        self.Layout_fr_pintu.setObjectName("Layout_fr_pintu")
        self.ic_ruang = QtWidgets.QLabel(self.fr_pintu)
        self.ic_ruang.setMinimumSize(QtCore.QSize(100, 0))
        self.ic_ruang.setMaximumSize(QtCore.QSize(80, 100))
        self.ic_ruang.setText("")
        self.ic_ruang.setPixmap(QtGui.QPixmap(":/icons/icon_set/door.png"))
        self.ic_ruang.setScaledContents(True)
        self.ic_ruang.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.ic_ruang.setObjectName("ic_ruang")
        self.Layout_fr_pintu.addWidget(self.ic_ruang)
        self.label = QtWidgets.QLabel(self.fr_pintu)
        self.label.setMinimumSize(QtCore.QSize(230, 0))
        self.label.setMaximumSize(QtCore.QSize(230, 16777215))
        self.label.setStyleSheet("color: rgb(238, 238, 236);\n"
"font: 75 30pt bold \"Roboto\";")
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.Layout_fr_pintu.addWidget(self.label)
        self.Layout_frame_info.addWidget(self.fr_pintu)
        self.Layout_main.addWidget(self.frame_info)
        self.frame_recog = QtWidgets.QFrame(self.main)
        self.frame_recog.setMinimumSize(QtCore.QSize(608, 0))
        self.frame_recog.setStyleSheet("background-color: none;")
        self.frame_recog.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_recog.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_recog.setObjectName("frame_recog")
        self.Layout_frame_recog = QtWidgets.QVBoxLayout(self.frame_recog)
        self.Layout_frame_recog.setContentsMargins(0, 0, 0, 9)
        self.Layout_frame_recog.setObjectName("Layout_frame_recog")
        self.fr_video = QtWidgets.QFrame(self.frame_recog)
        self.fr_video.setMinimumSize(QtCore.QSize(0, 450))
        self.fr_video.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_video.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_video.setObjectName("fr_video")
        self.Layout_fr_video = QtWidgets.QVBoxLayout(self.fr_video)
        self.Layout_fr_video.setObjectName("Layout_fr_video")
        self.lbl_video = QtWidgets.QLabel(self.fr_video)
        self.lbl_video.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_video.setObjectName("lbl_video")
        self.Layout_fr_video.addWidget(self.lbl_video)
        self.Layout_frame_recog.addWidget(self.fr_video)
        self.fr_name_plate = QtWidgets.QFrame(self.frame_recog)
        self.fr_name_plate.setMinimumSize(QtCore.QSize(300, 100))
        self.fr_name_plate.setMaximumSize(QtCore.QSize(99999, 100))
        self.fr_name_plate.setStyleSheet("border-radius:50px;\n"
"border-image: url(:/icons/icon_set/wadah nama.png);")
        self.fr_name_plate.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.fr_name_plate.setFrameShadow(QtWidgets.QFrame.Raised)
        self.fr_name_plate.setObjectName("fr_name_plate")
        self.Layout_fr_name_plate = QtWidgets.QHBoxLayout(self.fr_name_plate)
        self.Layout_fr_name_plate.setContentsMargins(18, -1, -1, -1)
        self.Layout_fr_name_plate.setObjectName("Layout_fr_name_plate")
        self.lbl_name_recog = QtWidgets.QLabel(self.fr_name_plate)
        self.lbl_name_recog.setMinimumSize(QtCore.QSize(70, 70))
        self.lbl_name_recog.setMaximumSize(QtCore.QSize(70, 70))
        self.lbl_name_recog.setStyleSheet("border-image: none;")
        self.lbl_name_recog.setText("")
        self.lbl_name_recog.setPixmap(QtGui.QPixmap(":/icons/icon_set/lock.png"))
        self.lbl_name_recog.setScaledContents(True)
        self.lbl_name_recog.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTop|QtCore.Qt.AlignTrailing)
        self.lbl_name_recog.setObjectName("lbl_name_recog")
        self.Layout_fr_name_plate.addWidget(self.lbl_name_recog)
        self.lbl_icon = QtWidgets.QLabel(self.fr_name_plate)
        self.lbl_icon.setMinimumSize(QtCore.QSize(400, 0))
        self.lbl_icon.setStyleSheet("font-size:35px; border-image: none;")
        self.lbl_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_icon.setObjectName("lbl_icon")
        self.Layout_fr_name_plate.addWidget(self.lbl_icon)
        self.lbl_counting = QtWidgets.QLabel(self.fr_name_plate)
        self.lbl_counting.setStyleSheet("border-image: none;")
        self.lbl_counting.setText("")
        self.lbl_counting.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_counting.setObjectName("lbl_counting")
        self.Layout_fr_name_plate.addWidget(self.lbl_counting)
        self.Layout_frame_recog.addWidget(self.fr_name_plate)
        self.Layout_main.addWidget(self.frame_recog)
        self.Layout_central_widget.addWidget(self.main)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AITI Check In"))
        self.lbl_jam.setText(_translate("MainWindow", "19:30"))
        self.lbl_tanggal.setText(_translate("MainWindow", "Fri, 29 Aug"))
        self.label_2.setText(_translate("MainWindow", "Press Call If You Not Yet Registed"))
        self.label.setText(_translate("MainWindow", "Ruang \n"
"Persalinan"))
        self.lbl_video.setText(_translate("MainWindow", "loading..."))
        self.lbl_icon.setText(_translate("MainWindow", "Unknown"))

import ui_icon_set_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

